from enum import StrEnum


class ErrorCode(StrEnum):
    AUTHENTICATION_FAILED = "DCC_AUTHENTICATION_FAILED"
    AUTHORIZATION_FAILED = "DCC_AUTHORIZATION_FAILED"
    REPLAY_REJECTED = "DCC_REPLAY_REJECTED"
    INVALID_EVENT = "DCC_INVALID_EVENT"
    IDEMPOTENCY_CONFLICT = "DCC_IDEMPOTENCY_CONFLICT"
    INVALID_TRANSITION = "DCC_INVALID_TRANSITION"
    CONCURRENCY_CONFLICT = "DCC_CONCURRENCY_CONFLICT"
    POLICY_REJECTED = "DCC_POLICY_REJECTED"
    PROVIDER_UNAVAILABLE = "DCC_PROVIDER_UNAVAILABLE"
    PROVIDER_RESPONSE_INVALID = "DCC_PROVIDER_RESPONSE_INVALID"
    PAYMENT_MISMATCH = "DCC_PAYMENT_MISMATCH"
    HUMAN_REVIEW_REQUIRED = "DCC_HUMAN_REVIEW_REQUIRED"
    INTERNAL_ERROR = "DCC_INTERNAL_ERROR"


class ServiceError(Exception):
    def __init__(self, code: ErrorCode, safe_message: str) -> None:
        self.code = code
        self.safe_message = safe_message
        super().__init__(safe_message)
